//enemyList
export const enemy = {
    banditNexdor: {
        name: 'Agressive Bandit',
        img: 'enemyFiles/bandit.png',
        attack: 5,
        defense: 5,
        luck: 2,
        defending: false,
        maxhp: 50,
        hp: 50,
        energy: 20,
        maxenergy: 20,
        healCost: 20,
        actions: ['attack', 'attack', 'waste'],
        waste: 'The bandit tries to make you flinch',
        drop: {
            attack: 2,
            defense: 2,
            hp: 5
        }
    },
    rats: {
        name: 'One Hundred Rats',
        img: 'enemyFiles/rats.png',
        attack: 3,
        defense: 1,
        luck: 5,
        defending: false,
        maxhp: 100,
        hp: 100,
        actions: ['attack', 'defend', 'waste'],
        waste: 'The rats gather in a circle to form a plan.',
        drop: {
            attack: 2,
            hp: 10
        }
    },
    fightChef: {
        name: 'Head Chef',
        img: 'enemyFiles/chef.png',
        attack: 5,
        defense: 5,
        luck: 2,
        defending: false,
        maxhp: 125,
        hp: 125,
        maxenergy: 40,
        energy: 40,
        healCost: 10,
        actions: ['attack', 'heal', 'defend', 'waste'],
        waste: 'Someone calls over the Chef to complain about thier food!',
        drop: {
            attack: 2,
            energy: 5,
            hp: 5
        }
    },
    sucker1: {
        name: 'Jerome the cowardly',
        attack: 1,
        defense: 8,
        luck: 1,
        defending: false,
        maxhp: 75,
        hp: 75,
        maxenergy: 40,
        energy: 40,
        healCost: 10,
        actions: ['heal', 'defend', 'waste'],
        waste: 'Jerome tries to hide behind you.',
        drop: {
            attack: 2,
            defense: 1,
            hp: 5,
            energy: 5,
        }
    },
    fight2: {
        name: 'Wallice the Great',
        attack: 8,
        defense: 5,
        luck: 3,
        defending: false,
        maxhp: 150,
        hp: 150,
        maxenergy: 40,
        energy: 40,
        healCost: 20,
        actions: ['attack', 'heal', 'defend', 'waste'],
        waste: 'Wallice is making snide remarks about the way you hold your sword.',
        drop: {
            attack: 2,
            defense: 1,
            hp: 5,
            energy: 5,
        }
    },
    fight3: {
        name: 'Primo the Brawler',
        attack: 9,
        defense: 6,
        luck: 1,
        defending: false,
        maxhp: 200,
        hp: 200,
        maxenergy: 0,
        energy: 0,
        healCost: 10,
        actions: ['attack', 'defend', 'waste'],
        waste: 'Primo looks into your soul.',
        drop: {
            attack: 2,
            defense: 1,
            hp: 10,
            energy: 10,
        }
    },
    battle4Tourn: {
        name: 'Old Man',
        attack: 10,
        defense: 7,
        luck: 4,
        defending: false,
        maxhp: 250,
        hp: 250,
        maxenergy: 40,
        energy: 40,
        healCost: 20,
        actions: ['attack', 'heal', 'defend', 'waste'],
        waste: 'The Old Man is taunting you to try him.'
    },
    mountainMan: {
        name: 'Old Man',
        attack: 11,
        defense: 10,
        luck: 4,
        defending: false,
        maxhp: 250,
        hp: 250,
        maxenergy: 40,
        energy: 40,
        healCost: 20,
        actions: ['attack', 'heal', 'defend', 'waste'],
        waste: 'The Old Man is taunting you to try him.'
    },
    fightBoss: {
        name: 'Big Cheese, the Boss',
        attack: 4,
        defense: 2,
        luck: 2,
        defending: false,
        maxhp: 300,
        hp: 300,
        maxenergy: 60,
        energy: 60,
        healCost: 20,
        actions: ['attack', 'heal', 'defend', 'waste'],
        waste: 'Big Cheese talks about how you don\'t want to mess with him.',
    },
    mountainSkelly: {
        name: 'Old Man',
        attack: 6,
        defense: 1,
        luck: 7,
        defending: false,
        maxhp: 50,
        hp: 50,
        maxenergy: 0,
        energy: 0,
        healCost: 20,
        actions: ['attack', 'defend', 'waste'],
        waste: 'The Skeleton forgets why he\'s here.',
        drop: {
            attack: 5,
            luck: 3,
            hp: 5,
            energy: 5,
        }
    },
    forcemoney: {
        name: 'Common housecitizen',
        attack: 1,
        defense: 8,
        luck: 1,
        defending: false,
        maxhp: 50,
        hp: 50,
        maxenergy: 40,
        energy: 40,
        healCost: 10,
        actions: ['attack', 'defend', 'waste', 'waste'],
        waste: 'The man tries to run, but trips!',
        drop: {
            attack: 4,
            hp: 5,
            energy: 5,
        }
    },
    battleHouse2: {
        name: 'Friendly Neighbor',
        attack: 1,
        defense: 4,
        luck: 1,
        defending: false,
        maxhp: 50,
        hp: 50,
        maxenergy: 40,
        energy: 40,
        healCost: 10,
        actions: ['heal', 'defend', 'waste'],
        waste: 'The Neighbor watches you carefully.',
        drop: {
            attack: 4,
            hp: 5,
            energy: 5,
        }
    },
    finalHouseBattle: {
        name: 'Bystanding Citizen',
        attack: 1,
        defense: 1,
        luck: 1,
        defending: false,
        maxhp: 5,
        hp: 5,
        maxenergy: 40,
        energy: 40,
        healCost: 10,
        actions: ['waste'],
        waste: 'The citizen is unaware of your presence.',
        drop: {
            attack: 2,
            defense: 1,
            hp: 10,
            energy: 5,
        }
    },
    heroCheese: {
        name: 'The Big Cheese (Hero)',
        attack: 5,
        defense: 10,
        luck: 3,
        defending: false,
        maxhp: 150,
        hp: 150,
        maxenergy: 40,
        energy: 40,
        healCost: 10,
        actions: ['heal', 'defend', 'waste', 'attack'],
        waste: 'The Big Cheese is relishing your hatred',
    },
    smallCheese: {
        name: 'The Big Cheese',
        attack: 3,
        defense: 5,
        luck: 3,
        defending: false,
        maxhp: 200,
        hp: 150,
        maxenergy: 40,
        energy: 40,
        healCost: 10,
        actions: ['heal', 'defend', 'waste', 'waste', 'attack'],
        waste: 'The Big Cheese is busy fighting off the crowd.',
        drop: {
            attack: 2,
            defense: 1,
            hp: 5,
            energy: 5,
        }
    },
    angryBoss: {
        name: 'The Big Cheese',
        attack: 3,
        defense: 8,
        luck: 2,
        defending: false,
        maxhp: 200,
        hp: 200,
        maxenergy: 40,
        energy: 40,
        healCost: 10,
        actions: ['heal', 'defend', 'waste', 'attack'],
        waste: 'The Big Cheese looks you down',
        drop: {
            attack: 2,
            defense: 1,
            hp: 5,
            energy: 5,
        }
    },
    fallback: {
        name: 'Jared Fast',
        img: 'enemyFiles/fastFallback.png',
        attack: 67,
        defense: 67,
        luck: 67,
        defending: false,
        maxhp: 1000,
        hp: 1000,
        maxenergy: 1000,
        energy: 1000,
        healCost: 0,
        actions: ['attack', 'heal', 'defend', 'waste'],
        waste: 'You have been spared a turn.',
        drop: {
            attack: 67,
            defense: 67,
            hp: 67,
            energy: 67,
        }
    }
};